#!/usr/bin/env python3
"""Build projects.qmd from one Markdown record per funded project."""

from __future__ import annotations

import html
from pathlib import Path

from content_records import records_in

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "projects.qmd"


def project_card(record: dict, index: int) -> str:
    facts = "".join(
        f"<div><dt>{html.escape(item['label'])}</dt><dd>{html.escape(item['value'])}</dd></div>"
        for item in record.get("facts", [])
    )
    return f"""<details class="project-card" {"open" if record.get("open", True) else ""}>
<summary>
<span class="project-index">{index:02d}</span>
<span class="project-summary-main">
<span class="project-grant">{html.escape(record["grant"])}</span>
<span class="project-title">{html.escape(record["title"])}</span>
</span>
<span class="project-toggle" aria-hidden="true"></span>
</summary>
<div class="project-body">
<div class="project-visual"><img src="{html.escape(record["image"])}" alt="{html.escape(record["image_alt"])}"></div>
<div class="project-copy">
<p class="project-lead">{html.escape(record["lead"])}</p>
{record["body"]}
<dl class="project-facts">{facts}</dl>
<div class="project-outputs">
<p class="project-outputs-label">Example papers <span>changes on reload</span></p>
<div class="project-paper-list" data-project-papers="{html.escape(record["paper_group"])}"></div>
</div>
</div>
</div>
</details>"""


def main() -> None:
    records = records_in(ROOT / "content" / "projects")
    cards = "\n\n".join(project_card(record, i) for i, record in enumerate(records, 1))
    OUTPUT.write_text(
        """---
title: "Projects"
description: "Funded research projects at the Caravagna Lab"
page-layout: full
title-block-banner: false
---

<!-- Generated by scripts/build_projects_page.py. Edit content/projects/*.md. -->
::: {.projects-page}
::: {.projects-heading}
<p class="eyebrow">Research · Projects</p>

# Funded research

Our projects connect methodological development with biological questions, experimental design and clinical collaboration.
:::

<div class="projects-list">
"""
        + cards
        + """
</div>
<script src="assets/projects-papers.js" defer></script>
:::
""",
        encoding="utf-8",
    )
    print(f"Projects page: {len(records)} Markdown records")


if __name__ == "__main__":
    main()
