#!/usr/bin/env python3
"""Build talks.qmd from Markdown engagement records."""

from __future__ import annotations

import html
from pathlib import Path

from content_records import records_in

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "talks.qmd"


def item(record: dict) -> str:
    badge = html.escape(record.get("badge", "Watch"))
    video = ""
    if record.get("thumbnail"):
        video = (
            f'<a class="engagement-video" href="{html.escape(record["url"])}" target="_blank" rel="noopener" '
            f'aria-label="{html.escape(record.get("aria_label", record["title"]))}">'
            f'<img src="{html.escape(record["thumbnail"])}" alt=""><span><i class="bi bi-play-fill" '
            f'aria-hidden="true"></i> {badge}</span></a>'
        )
    return f"""<article class="engagement-item">
<div class="engagement-year">{record["year"]}</div>
<div>
<h3><a href="{html.escape(record["url"])}" target="_blank" rel="noopener">{html.escape(record["title"])} <i class="bi bi-play-circle" aria-hidden="true"></i></a></h3>
<p class="engagement-meta">{html.escape(record["venue"])}</p>
{record["body"]}
</div>
{video}
</article>"""


def main() -> None:
    records = records_in(ROOT / "content" / "talks")
    sections = []
    definitions = [
        ("scientific", "Scientific presentations", "Methods, data and tumour evolution.", "Selected lectures for researchers, students and interdisciplinary audiences."),
        ("outreach", "Outreach", "Computational science in public.", "Activities for schools, universities, science festivals and general audiences."),
    ]
    for category, eyebrow, title, description in definitions:
        entries = "\n".join(item(record) for record in records if record["category"] == category)
        extra = " engagement-outreach" if category == "outreach" else ""
        sections.append(
            f'<section class="engagement-section{extra}"><div class="engagement-section-heading">'
            f'<p class="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{description}</p></div>'
            f'<div class="engagement-list">{entries}</div></section>'
        )
    OUTPUT.write_text(
        """---
title: "Talks & Outreach"
description: "Scientific presentations and public engagement from the Caravagna Lab"
page-layout: full
title-block-banner: false
---

<!-- Generated by scripts/build_talks_page.py. Edit content/talks/*.md. -->
::: {.engagement-page}
<header class="engagement-heading">
<p class="eyebrow">Talks & Outreach</p>
<h1>Ideas shared beyond the lab.</h1>
<p>Scientific lectures, educational activities and public conversations about cancer data science, tumour evolution and artificial intelligence.</p>
<div class="engagement-links">
<a href="mailto:gcaravagna@units.it?subject=Invitation%20to%20speak%20%E2%80%94%20Caravagna%20Lab"><i class="bi bi-envelope" aria-hidden="true"></i> Invite us to speak</a>
</div>
</header>
"""
        + "\n".join(sections)
        + "\n:::\n",
        encoding="utf-8",
    )
    print(f"Talks page: {len(records)} Markdown records")


if __name__ == "__main__":
    main()
