#!/usr/bin/env python3
"""Build the Join-us role-card include from Markdown records."""

from __future__ import annotations

import html
from pathlib import Path

from content_records import records_in

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "includes" / "join-opportunities.html"


def main() -> None:
    records = records_in(ROOT / "content" / "opportunities")
    cards = []
    for index, record in enumerate(records, 1):
        extra = ""
        if record.get("link_url"):
            extra = (
                f'<a class="join-card-link" href="{html.escape(record["link_url"])}" '
                f'target="_blank" rel="noopener"><i class="bi bi-{html.escape(record.get("link_icon", "arrow-up-right"))}"></i> '
                f'{html.escape(record["link_label"])}</a>'
            )
        cards.append(
            f'<article class="join-role-card"><span>{index:02d} · {html.escape(record["label"])}</span>'
            f'<h3>{html.escape(record["title"])}</h3>{record["body"]}{extra}</article>'
        )
    OUTPUT.parent.mkdir(exist_ok=True)
    OUTPUT.write_text(
        "<!-- Generated by scripts/build_join_opportunities.py. Edit content/opportunities/*.md. -->\n"
        + "\n".join(cards)
        + "\n",
        encoding="utf-8",
    )
    print(f"Join opportunities: {len(records)} Markdown records")


if __name__ == "__main__":
    main()
